# Generated by Django 4.2.30 on 2026-09-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active_on_field',
            field=models.BooleanField(default=True),
        ),
    ]
